##################################################################################
# Only this file is to be changed when running the pipeline
# (and the Snakefile rule all and maybe pipeline_job.sh for cluster submission)
##################################################################################


#--- Requires individual changes --------------------------------------------------

# This pipeline is mainly built for hybridization-capture based NGS data, but is also implements changes required for amplicon sequencing data.
# Amplicon seg. data? Consequence: no flagging of PCR duplicates (all of the amplified reads are in fact PCR duplicates by design) 
amplicon: false

# If amplicon, set this to false to ignore off-target reads (theoretically, no off-target reads are sequenced with amplicon-based capture).
# If the reference is filtered or masked, probably best to not consider off-targets reads.
consider_off_targets: true

# Do the samples require specific preprocessing for unique molecular identifiers (UMIs)? (Specifically for HRD dataset)
contain_UMIs: true

# Mask regions of interest in the reference genome? If yes, specify the amount of bp padding around the regions of interest.
mask_reference: false
padding: 500 # 500 is appr. NGS fragment size

# compute mappability for the reference genome or download the premade one from CNVkit?
compute_mappability: false

# compute or download reference dictionary?
compute_dict: false

# hard code sex? Useful for ovarian cancer, for example.
sex:
  hard_code: false # set to true if you want to hard code
  sex:  'F' # female or male?

# For hg19, chromosome / contig names must be of type "chr1" for hg38 and "1" in the paneldesign.
panel_design: "resources/paneldesign/all_covered_annot_no_chr.bed"

# genome version
genome_version: "hg19" # valid options: "hg38", "hg19" (-> version b37 as required by Mutect2)

# Path to reference genome and its index file. Will be downloaded if absent. Current pipeline settings are for hg38.
reference_hg38:
  fasta: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg38/ucsc/hg38.fa"
  index: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg38/ucsc/hg38.fa.fai"
# fasta: "resources/reference/hg38.fa" # use this if you wish to download the reference file
# ref_index: "resources/reference/hg38.fa.fai"
  dict: "resources/reference/hg38.dict"
  fa_genome: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg38/ucsc/hg38.fa.genome"
  fasta_link: "storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta"
  index_link: "storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta.fai"
  dict_link: "storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dict"

reference_hg19:
  # fasta: "/data/cephfs-1/work/projects/cubit/20.05/static_data/app_support/GATK_bundle/b37/human_g1k_v37.fasta"
  fasta: "resources/reference/human_g1k_v37.fasta"
  # index: "/data/cephfs-1/work/projects/cubit/20.05/static_data/app_support/GATK_bundle/b37/human_g1k_v37.fasta.fai"
  index: "resources/reference/human_g1k_v37.fasta.fai"
  dict: "resources/reference/human_g1k_v37.dict"
  fa_genome: "TBD"
  fasta_link: "https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta"
  index_link: "https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.fai"
  dict_link: "https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.dict"

data:
  samples_in_directory: false # boolean, are samples or their symlinks in resource/data?
  # if previous is false, give path to sample sheet
  sample_sheet_path: "resources/data/sample_sheet_test.tsv" # tab-separated columns: sample|fq1|fq2

# first run with generic reference or second run with chosen samples as panel of normals (PON) for CNVkit?
pon:
  second_run_with_pon: false # set to true when this is the second run with a PON
  reference_sample_names: "resources/data/lowpurity_samples.tsv" # list of sample names chosen for PON creation, leave it empty if previous is false
  directory_suffix: "lowpurity" # if testing multiple PON versions, describe the current one here

# If true normal samples are available, you can create a pon.rds panel of normals file with PureCN and use it with this pipeline.
pon_rds:
  use_true_pon_instead: true # set to true if you want to use a true pon.rds
  rds: "resources/true_pon/normaldb.rds" # path to rds file
  intervals_file: "resources/paneldesign/intervals.txt.no_chr.txt" # path to normalized intervals file
  fasta: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg19/ucsc/hg19.fa" # fasta reference file used to create pon.rds and intervals file, if applicable
  chain_file: "resources/reference/b37tohg19.chain" # chain file for liftover, if applicable
  mapping_bias: "resources/true_pon/mapping-bias-file.rds" # mapping bias rds file used with PureCN
  blacklist: "resources/true_pon/hg19_simpleRepeats.bed"


#--- Do usually not require changes ---------------------------------------------

adapter_sequences: "resources/adapter/panel-adapter.fa" # for trimming

qualimap_bed: "resources/paneldesign/paneldesign_forQualimap.bed"

# The paths to reference files which will be downloaded if absent

gnomad_af_only_hg38:
  vcf: "resources/germline-resource/af-only-gnomad.hg38.vcf.gz"
  index: "resources/germline-resource/af-only-gnomad.hg38.vcf.gz.tbi"
  vcf_link: "www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz"
  index_link: "www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz.tbi"

gnomad_af_only_hg19:
  vcf: "/fast/work/groups/cubi/projects/biotools/static_data/app_support/GATK/b37/af-only-gnomad.raw.sites.vcf.gz"
  index: "/fast/work/groups/cubi/projects/biotools/static_data/app_support/GATK/b37/af-only-gnomad.raw.sites.vcf.gz.tbi"
  vcf_link: "https://www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.raw.sites.grch37.vcf.gz" # not tested
  index_link: "https://www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.raw.sites.grch37.vcf.gz.tbi"

common_germline_variants_hg38:
  vcf: "resources/common-biallelic/small_exac_common_3.hg38.vcf.gz"
  index: "resources/common-biallelic/small_exac_common_3.hg38.vcf.gz.tbi"
  vcf_link: "http://storage.googleapis.com/gatk-best-practices/somatic-hg38/small_exac_common_3.hg38.vcf.gz"
  index_link: "http://storage.googleapis.com/gatk-best-practices/somatic-hg38/small_exac_common_3.hg38.vcf.gz.tbi"

common_germline_variants_hg19:
  vcf: "/fast/work/groups/cubi/projects/biotools/static_data/app_support/GATK/b37/small_exac_common_3.vcf.gz"
  index: "/fast/work/groups/cubi/projects/biotools/static_data/app_support/GATK/b37/small_exac_common_3.vcf.gz.tbi"
  vcf_link: "https://raw.githubusercontent.com/pedricolino/cnakepit/main/config/config.yaml"
  index_link: "https://raw.githubusercontent.com/pedricolino/cnakepit/main/config/config.yaml"

mappability_hg38:
  bed: "resources/mappability/access.bed"
  link: "github.com/etal/cnvkit/raw/master/data/access-5k-mappable.hg19.bed"

mappability_hg19:
  bed: "resources/mappability/access.bed"
  link: "https://raw.githubusercontent.com/pedricolino/cnakepit/main/config/config.yaml" # TBD, placeholder

sv_blacklist_hg38:
  bed: "resources/mappability/sv_blacklist.bed"
  link: "http://cf.10xgenomics.com/supp/genome/GRCh38/sv_blacklist.bed"

sv_blacklist_hg19:
  bed: "/fast/work/groups/cubi/projects/biotools/xTea/rep_lib_annotation/blacklist/hg19/sv_blacklist.bed"
  link: "https://raw.githubusercontent.com/pedricolino/cnakepit/main/config/config.yaml" # TBD, placeholder

masked_ref: "resources/reference/masked.fa"

#--- variance calling parameters: bcf tools --------------------------------------

# bcftools call:
# caller: valid options include -c/--consensus-caller or -m/--multiallelic-caller
caller: "-m"
# other options e.g. "--ploidy 1 --prior 0.001"
caller_options: "--ploidy 1 --prior 0.001"

# bcftools mpileup:
# e.g. "--max-depth 100 --min-BQ 15"
mpileup_options: "--max-depth 100 --min-BQ 15"



#TESTING PURPOSES:
ref_fil: "resources/filter_ref/hg38_filtered.fa"
