##################################################################################
# Only this file is to be changed when running the pipeline
# (and the Snakefile rule all and maybe pipeline_job.sh for cluster submission)
##################################################################################


#--- Requires individual changes --------------------------------------------------

# Use existing conda environments (must be the same names) or create new ones just for this pipeline?
conda_envs:
  use_existing_envs: true
  envs_path: "~/work/miniforge3/envs/" # path to conda envs if use_existing_envs is true

# This pipeline is mainly built for hybridization-capture based NGS data, but is also implements changes required for amplicon sequencing data.
# Amplicon seg. data? Consequence: no flagging of PCR duplicates (all of the amplified reads are in fact PCR duplicates by design) 
amplicon: false

# If amplicon, set this to false to ignore off-target reads (theoretically, no off-target reads are sequenced with amplicon-based capture).
# If the reference is filtered or masked, probably best to not consider off-targets reads.
consider_off_targets: true

# Do the samples require specific preprocessing for unique molecular identifiers (UMIs)? (Specifically for HRD dataset)
contain_UMIs: false

# Mask regions of interest in the reference genome? If yes, specify the amount of bp padding around the regions of interest.
mask_reference: false
padding: 500 # 500 is appr. NGS fragment size

# compute mappability for the reference genome or download the premade one from CNVkit?
compute_mappability: false

# which aligner should be used? Options: "bwa" or "bwa-mem2"
aligner: "bwa-mem2"

# are there different lanes for the same sample? If yes, the pipeline will merge the lanes after alignment
different_lanes: false

# compute or download reference dictionary?
compute_dict: false

# compute or use precomputed reference index files for bwa?
compute_bwa_indices: true

# hard code sex? Useful for ovarian cancer, for example.
sex:
  hard_code: false # set to true if you want to hard code
  sex:  'F' # female or male?

# For hg19, chromosome / contig names must be of type "chr1" for hg38 and "1" in the paneldesign.
panel_design: "/data/cephfs-1/home/users/cemo10_c/work/project_symlinks/crc/work/pipeline_pdo_ce14/panel/S33266436_Regions_no_chr.bed"

# VEP for maf2vcf
vep:
  executable: "/data/cephfs-1/home/users/cemo10_c/work/miniforge3/envs/vcf2maf/bin"
  data: "resources/vep/hg37" # usually the homo_sapiens folder should be in there

# refgene for gistic
gistic:
  refgene: "~/work/miniforge3/envs/gistic/share/gistic2-2.0.23-1/refgenefiles/hg19.mat"
  conf_level: 0.75

# genome version
genome_version: "hg19" # valid options: "hg38", "hg19" (-> version b37 as required by Mutect2)

# Path to reference genome and its index file. Will be downloaded if absent. Current pipeline settings are for hg38.
reference_hg38:
  fasta: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg38/ucsc/hg38.fa"
  index: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg38/ucsc/hg38.fa.fai"
# fasta: "resources/reference/hg38.fa" # use this if you wish to download the reference file
# ref_index: "resources/reference/hg38.fa.fai"
  dict: "resources/reference/hg38.dict"
  bwa_indices: "/data/cephfs-1/work/projects/cubit/20.05/static_data/precomputed/BWA/0.7.17/hg38/ucsc/hg38.fa"
  fa_genome: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/hg38/ucsc/hg38.fa.genome"
  fasta_link: "storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta"
  index_link: "storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta.fai"
  dict_link: "storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dict"

reference_hg19:
  # fasta: "/data/cephfs-1/work/projects/cubit/20.05/static_data/app_support/GATK_bundle/b37/human_g1k_v37.fasta"
  fasta: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/GRCh37/g1k_phase1/human_g1k_v37.fasta"
  # index: "/data/cephfs-1/work/projects/cubit/20.05/static_data/app_support/GATK_bundle/b37/human_g1k_v37.fasta.fai"
  index: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/GRCh37/g1k_phase1/human_g1k_v37.fasta.fai"
  dict: "/data/cephfs-1/work/projects/cubit/20.05/static_data/reference/GRCh37/g1k_phase1/human_g1k_v37.dict"
  bwa_indices: "TBD"
  fa_genome: "TBD"
  fasta_link: "https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta"
  index_link: "https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta.fai"
  dict_link: "https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.dict"

data:
  samples_in_directory: false # boolean, are samples or their symlinks in resource/data?
  # if previous is false, give path to sample sheet
  sample_sheet_path: "resources/data/sample_sheet.tsv" # tab-separated columns: sample|fq1|fq2
  # sample_sheet_path: "resources/data/benchmarking_samples_sheet.tsv" # selected samples to compare to gold standard
# first run with generic reference or second run with chosen samples as panel of normals (PON) for CNVkit?
pon:
  second_run_with_pon: false # set to true when this is the second run with a PON
  reference_sample_names: "resources/data/all_samplenames.tsv" # list of sample names chosen for PON creation, leave it empty if previous is false
  directory_suffix: "cohort" # if testing multiple PON versions, describe the current one here

# If true normal samples are available, you can create a pon.rds panel of normals file with PureCN and use it with this pipeline.
pon_rds:
  use_true_pon_instead: false # set to true if you want to use a true pon.rds
  rds: "resources/true_pon/normalDB_hg19.rds" # path to rds file
  intervals_file: "resources/paneldesign/baits_hg19_intervals.txt" # path to normalized intervals file
  different_contigs: false # set to true if the reference genome is different from the one used to create the pon.rds (e.g. GATK's b37 aka hg19 vs actual hg19)
  fasta: "resources/reference/human_g1k_v37.fasta" # fasta reference file used to create pon.rds and intervals file, if applicable
  chain_file: "resources/reference/b37tohg19.chain" # chain file for liftover, if applicable
  mapping_bias_available: true # set to true if mapping bias file is available and give location in next line
  mapping_bias: "resources/mappability/mapping_bias_hg19.rds" # mapping bias rds file used with PureCN
  different_blacklist: false # set to true if the blacklist file is different from the one in sv_blacklist_hg19 below
  blacklist: "resources/true_pon/hg19_simpleRepeats.bed"


#--- Do usually not require changes ---------------------------------------------

adapter_sequences: "resources/adapter/panel-adapter.fa" # for trimming

qualimap_bed: "/data/cephfs-1/home/users/cemo10_c/work/project_symlinks/crc/work/pipeline_pdo_ce14/panel/S33266436_Regions_no_chr.bed"
# qualimap_bed: "resources/paneldesign/paneldesign_forQualimap.bed" # set to this if it fails with the normal BED file

# The paths to reference files which will be downloaded if absent

gnomad_af_only_hg38:
  vcf: "resources/germline-resource/af-only-gnomad.hg38.vcf.gz"
  index: "resources/germline-resource/af-only-gnomad.hg38.vcf.gz.tbi"
  vcf_link: "www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz"
  index_link: "www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz.tbi"

gnomad_af_only_hg19:
  vcf: "/data/cephfs-1/work/groups/cubi/projects/biotools/GATK_Best_Practices/somatic-b37/af-only-gnomad.raw.sites.vcf.gz"
  index: "/data/cephfs-1/work/groups/cubi/projects/biotools/GATK_Best_Practices/somatic-b37/af-only-gnomad.raw.sites.vcf.gz.tbi"
  vcf_link: "https://www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.raw.sites.grch37.vcf.gz" # not tested
  index_link: "https://www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.raw.sites.grch37.vcf.gz.tbi"

common_germline_variants_hg38:
  vcf: "resources/common-biallelic/small_exac_common_3.hg38.vcf.gz"
  index: "resources/common-biallelic/small_exac_common_3.hg38.vcf.gz.tbi"
  vcf_link: "http://storage.googleapis.com/gatk-best-practices/somatic-hg38/small_exac_common_3.hg38.vcf.gz"
  index_link: "http://storage.googleapis.com/gatk-best-practices/somatic-hg38/small_exac_common_3.hg38.vcf.gz.tbi"

common_germline_variants_hg19:
  vcf: "/data/cephfs-1/work/groups/cubi/projects/biotools/GATK_Best_Practices/somatic-b37/small_exac_common_3.vcf.gz"
  index: "/data/cephfs-1/work/groups/cubi/projects/biotools/GATK_Best_Practices/somatic-b37/small_exac_common_3.vcf.gz.tbi"
  vcf_link: "https://raw.githubusercontent.com/pedricolino/cnakepit/main/config/config.yaml"
  index_link: "https://raw.githubusercontent.com/pedricolino/cnakepit/main/config/config.yaml"

mappability_hg38:
  bed: "resources/mappability/access.bed"
  link: "github.com/etal/cnvkit/raw/master/data/access-10kb.hg38.bed"

mappability_hg19:
  bed: "resources/mappability/access.bed"
  # bed: "resources/mappability/access_no_chr.bed"
  link: "github.com/etal/cnvkit/raw/master/data/access-10kb.hg19.bed"

sv_blacklist_hg38:
  bed: "resources/sv_blacklist/sv_blacklist_hg38.bed"
  link: "http://cf.10xgenomics.com/supp/genome/GRCh38/sv_blacklist.bed"

sv_blacklist_hg19:
  bed: "resources/sv_blacklist/simpleRepeat.bed"
  # bed: "resources/sv_blacklist/simpleRepeat_no_chr.txt.gz"
  link: "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/simpleRepeat.txt.gz"

masked_ref: "resources/reference/masked.fa"

#--- variance calling parameters: bcf tools --------------------------------------

# bcftools call:
# caller: valid options include -c/--consensus-caller or -m/--multiallelic-caller
caller: "-m"
# other options e.g. "--ploidy 1 --prior 0.001"
caller_options: "--ploidy 1 --prior 0.001"

# bcftools mpileup:
# e.g. "--max-depth 100 --min-BQ 15"
mpileup_options: "--max-depth 100 --min-BQ 15"


#TESTING PURPOSES:
ref_fil: "resources/filter_ref/hg38_filtered.fa"
